package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CB_ChaoBiaoGJ.
 */
public class ChaoBiaoGJ {

    private int ID;
    /** Not-null value. */
    private String S_CH;
    /** Not-null value. */
    private String S_CID;
    private long D_CHAOBIAOSJ;
    private int I_TYPE;
    /** Not-null value. */
    private String S_X;
    /** Not-null value. */
    private String S_Y;

    private String S_ACCOUNT;

    private int I_RENWUBH;

    private int mForeignIndex; // only store in memory, not in database

    public ChaoBiaoGJ() {
    }

    public ChaoBiaoGJ(int ID, String S_CH, String S_CID, long D_CHAOBIAOSJ, int I_TYPE, String S_X, String S_Y,String S_ACCOUNT,int I_RENWUBH) {
        this.ID = ID;
        this.S_CH = S_CH;
        this.S_CID = S_CID;
        this.D_CHAOBIAOSJ = D_CHAOBIAOSJ;
        this.I_TYPE = I_TYPE;
        this.S_X = S_X;
        this.S_Y = S_Y;
        this.S_ACCOUNT = S_ACCOUNT;
        this.I_RENWUBH = I_RENWUBH;
    }


    public int getI_RENWUBH() {
        return I_RENWUBH;
    }

    public void setI_RENWUBH(int i_RENWUBH) {
        I_RENWUBH = i_RENWUBH;
    }

    public String getS_ACCOUNT() {
        return S_ACCOUNT;
    }

    public void setS_ACCOUNT(String s_ACCOUNT) {
        S_ACCOUNT = s_ACCOUNT;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getS_CH() {
        return S_CH;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CH(String S_CH) {
        this.S_CH = S_CH;
    }

    /** Not-null value. */
    public String getS_CID() {
        return S_CID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    public long getD_CHAOBIAOSJ() {
        return D_CHAOBIAOSJ;
    }

    public void setD_CHAOBIAOSJ(long D_CHAOBIAOSJ) {
        this.D_CHAOBIAOSJ = D_CHAOBIAOSJ;
    }

    public int getI_TYPE() {
        return I_TYPE;
    }

    public void setI_TYPE(int I_TYPE) {
        this.I_TYPE = I_TYPE;
    }

    /** Not-null value. */
    public String getS_X() {
        return S_X;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_X(String S_X) {
        this.S_X = S_X;
    }

    /** Not-null value. */
    public String getS_Y() {
        return S_Y;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_Y(String S_Y) {
        this.S_Y = S_Y;
    }

    public int getmForeignIndex() {
        return mForeignIndex;
    }

    public void setmForeignIndex(int mForeignIndex) {
        this.mForeignIndex = mForeignIndex;
    }
}
