package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PDA_YANCHI.
 */
public class YanChiBiao {

    private Integer ID;
    private Integer I_RENWUBH;
    private Integer I_CHAOBIAOID;
    private String S_CID;
    private Integer I_CHAOJIANSL;
    private Integer I_SHANGCICM;
    private Integer I_CHAOHUICM;
    private Integer I_ZHUANGTAIBM;
    private String S_ZHUANGTAIMC;
    private Integer I_LIANGGAOLDBM;
    private Integer D_CHAOBIAORQ;
    private Integer I_CHAOBIAON;
    private Integer I_CHAOBIAOY;
    private String S_CHAOBIAOY;
    private Integer I_FANGSHIBM;
    private Integer I_CHAOBIAOZT;
    private Integer D_SHANGCICBRQ;
    private String S_ST;
    private String S_CH;
    private Integer I_CENEIXH;
    private Integer I_JIUBIAOCM;
    private Integer I_XINBIAODM;
    private Integer D_HUANBIAORQ;
    private Integer D_HUANBIAOHTSJ;
    private Integer D_DENGJISJ;
    private Integer I_ZHUANGTAI;
    private String S_YANCHIYBH;
    private String S_HUITIANYBH;
    private Integer D_HUITIANSJ;
    private String S_CHULIQK;
    private String S_CAOZUOR;
    private Integer D_CAOZUOSJ;
    private Integer I_HUANBIAOFS;
    private String S_CHAOBIAOBZ;
    private String S_SHUIBIAOTXM;
    private String S_YANCHIYY;
    private Integer I_ZHENSHICM;
    private Integer I_LINYONGSLSM;
    private String S_X;
    private String S_Y;
    private Integer I_YANCHILX;
    private String S_YANCHIBH;
    private Integer I_CHAOBIAOBZ;
    private Integer I_ShangChuanBZ;
    private Integer I_KaiZhangBZ;
    private String S_JH;
    private Integer I_LIANGGAOSL;
    private Integer I_LIANGDISL;
    private Integer I_PINGJUNL1;
    private Integer I_SHANGCISL;
    private Integer N_JE;
    private String S_JIETITS;
    private String S_ShangCiZTBM;

    public YanChiBiao() {
    }

    public YanChiBiao(Integer ID, Integer I_RENWUBH, Integer I_CHAOBIAOID, String S_CID, Integer I_CHAOJIANSL, Integer I_SHANGCICM, Integer I_CHAOHUICM, Integer I_ZHUANGTAIBM, String S_ZHUANGTAIMC, Integer I_LIANGGAOLDBM, Integer D_CHAOBIAORQ, Integer I_CHAOBIAON, Integer I_CHAOBIAOY, String S_CHAOBIAOY, Integer I_FANGSHIBM, Integer I_CHAOBIAOZT, Integer D_SHANGCICBRQ, String S_ST, String S_CH, Integer I_CENEIXH, Integer I_JIUBIAOCM, Integer I_XINBIAODM, Integer D_HUANBIAORQ, Integer D_HUANBIAOHTSJ, Integer D_DENGJISJ, Integer I_ZHUANGTAI, String S_YANCHIYBH, String S_HUITIANYBH, Integer D_HUITIANSJ, String S_CHULIQK, String S_CAOZUOR, Integer D_CAOZUOSJ, Integer I_HUANBIAOFS, String S_CHAOBIAOBZ, String S_SHUIBIAOTXM, String S_YANCHIYY, Integer I_ZHENSHICM, Integer I_LINYONGSLSM, String S_X, String S_Y, Integer I_YANCHILX, String S_YANCHIBH, Integer I_CHAOBIAOBZ, Integer I_ShangChuanBZ, Integer I_KaiZhangBZ, String S_JH, Integer I_LIANGGAOSL, Integer I_LIANGDISL, Integer I_PINGJUNL1, Integer I_SHANGCISL, Integer N_JE, String S_JIETITS, String S_ShangCiZTBM) {
        this.ID = ID;
        this.I_RENWUBH = I_RENWUBH;
        this.I_CHAOBIAOID = I_CHAOBIAOID;
        this.S_CID = S_CID;
        this.I_CHAOJIANSL = I_CHAOJIANSL;
        this.I_SHANGCICM = I_SHANGCICM;
        this.I_CHAOHUICM = I_CHAOHUICM;
        this.I_ZHUANGTAIBM = I_ZHUANGTAIBM;
        this.S_ZHUANGTAIMC = S_ZHUANGTAIMC;
        this.I_LIANGGAOLDBM = I_LIANGGAOLDBM;
        this.D_CHAOBIAORQ = D_CHAOBIAORQ;
        this.I_CHAOBIAON = I_CHAOBIAON;
        this.I_CHAOBIAOY = I_CHAOBIAOY;
        this.S_CHAOBIAOY = S_CHAOBIAOY;
        this.I_FANGSHIBM = I_FANGSHIBM;
        this.I_CHAOBIAOZT = I_CHAOBIAOZT;
        this.D_SHANGCICBRQ = D_SHANGCICBRQ;
        this.S_ST = S_ST;
        this.S_CH = S_CH;
        this.I_CENEIXH = I_CENEIXH;
        this.I_JIUBIAOCM = I_JIUBIAOCM;
        this.I_XINBIAODM = I_XINBIAODM;
        this.D_HUANBIAORQ = D_HUANBIAORQ;
        this.D_HUANBIAOHTSJ = D_HUANBIAOHTSJ;
        this.D_DENGJISJ = D_DENGJISJ;
        this.I_ZHUANGTAI = I_ZHUANGTAI;
        this.S_YANCHIYBH = S_YANCHIYBH;
        this.S_HUITIANYBH = S_HUITIANYBH;
        this.D_HUITIANSJ = D_HUITIANSJ;
        this.S_CHULIQK = S_CHULIQK;
        this.S_CAOZUOR = S_CAOZUOR;
        this.D_CAOZUOSJ = D_CAOZUOSJ;
        this.I_HUANBIAOFS = I_HUANBIAOFS;
        this.S_CHAOBIAOBZ = S_CHAOBIAOBZ;
        this.S_SHUIBIAOTXM = S_SHUIBIAOTXM;
        this.S_YANCHIYY = S_YANCHIYY;
        this.I_ZHENSHICM = I_ZHENSHICM;
        this.I_LINYONGSLSM = I_LINYONGSLSM;
        this.S_X = S_X;
        this.S_Y = S_Y;
        this.I_YANCHILX = I_YANCHILX;
        this.S_YANCHIBH = S_YANCHIBH;
        this.I_CHAOBIAOBZ = I_CHAOBIAOBZ;
        this.I_ShangChuanBZ = I_ShangChuanBZ;
        this.I_KaiZhangBZ = I_KaiZhangBZ;
        this.S_JH = S_JH;
        this.I_LIANGGAOSL = I_LIANGGAOSL;
        this.I_LIANGDISL = I_LIANGDISL;
        this.I_PINGJUNL1 = I_PINGJUNL1;
        this.I_SHANGCISL = I_SHANGCISL;
        this.N_JE = N_JE;
        this.S_JIETITS = S_JIETITS;
        this.S_ShangCiZTBM = S_ShangCiZTBM;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public Integer getI_RENWUBH() {
        return I_RENWUBH;
    }

    public void setI_RENWUBH(Integer I_RENWUBH) {
        this.I_RENWUBH = I_RENWUBH;
    }

    public Integer getI_CHAOBIAOID() {
        return I_CHAOBIAOID;
    }

    public void setI_CHAOBIAOID(Integer I_CHAOBIAOID) {
        this.I_CHAOBIAOID = I_CHAOBIAOID;
    }

    public String getS_CID() {
        return S_CID;
    }

    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    public Integer getI_CHAOJIANSL() {
        return I_CHAOJIANSL;
    }

    public void setI_CHAOJIANSL(Integer I_CHAOJIANSL) {
        this.I_CHAOJIANSL = I_CHAOJIANSL;
    }

    public Integer getI_SHANGCICM() {
        return I_SHANGCICM;
    }

    public void setI_SHANGCICM(Integer I_SHANGCICM) {
        this.I_SHANGCICM = I_SHANGCICM;
    }

    public Integer getI_CHAOHUICM() {
        return I_CHAOHUICM;
    }

    public void setI_CHAOHUICM(Integer I_CHAOHUICM) {
        this.I_CHAOHUICM = I_CHAOHUICM;
    }

    public Integer getI_ZHUANGTAIBM() {
        return I_ZHUANGTAIBM;
    }

    public void setI_ZHUANGTAIBM(Integer I_ZHUANGTAIBM) {
        this.I_ZHUANGTAIBM = I_ZHUANGTAIBM;
    }

    public String getS_ZHUANGTAIMC() {
        return S_ZHUANGTAIMC;
    }

    public void setS_ZHUANGTAIMC(String S_ZHUANGTAIMC) {
        this.S_ZHUANGTAIMC = S_ZHUANGTAIMC;
    }

    public Integer getI_LIANGGAOLDBM() {
        return I_LIANGGAOLDBM;
    }

    public void setI_LIANGGAOLDBM(Integer I_LIANGGAOLDBM) {
        this.I_LIANGGAOLDBM = I_LIANGGAOLDBM;
    }

    public Integer getD_CHAOBIAORQ() {
        return D_CHAOBIAORQ;
    }

    public void setD_CHAOBIAORQ(Integer D_CHAOBIAORQ) {
        this.D_CHAOBIAORQ = D_CHAOBIAORQ;
    }

    public Integer getI_CHAOBIAON() {
        return I_CHAOBIAON;
    }

    public void setI_CHAOBIAON(Integer I_CHAOBIAON) {
        this.I_CHAOBIAON = I_CHAOBIAON;
    }

    public Integer getI_CHAOBIAOY() {
        return I_CHAOBIAOY;
    }

    public void setI_CHAOBIAOY(Integer I_CHAOBIAOY) {
        this.I_CHAOBIAOY = I_CHAOBIAOY;
    }

    public String getS_CHAOBIAOY() {
        return S_CHAOBIAOY;
    }

    public void setS_CHAOBIAOY(String S_CHAOBIAOY) {
        this.S_CHAOBIAOY = S_CHAOBIAOY;
    }

    public Integer getI_FANGSHIBM() {
        return I_FANGSHIBM;
    }

    public void setI_FANGSHIBM(Integer I_FANGSHIBM) {
        this.I_FANGSHIBM = I_FANGSHIBM;
    }

    public Integer getI_CHAOBIAOZT() {
        return I_CHAOBIAOZT;
    }

    public void setI_CHAOBIAOZT(Integer I_CHAOBIAOZT) {
        this.I_CHAOBIAOZT = I_CHAOBIAOZT;
    }

    public Integer getD_SHANGCICBRQ() {
        return D_SHANGCICBRQ;
    }

    public void setD_SHANGCICBRQ(Integer D_SHANGCICBRQ) {
        this.D_SHANGCICBRQ = D_SHANGCICBRQ;
    }

    public String getS_ST() {
        return S_ST;
    }

    public void setS_ST(String S_ST) {
        this.S_ST = S_ST;
    }

    public String getS_CH() {
        return S_CH;
    }

    public void setS_CH(String S_CH) {
        this.S_CH = S_CH;
    }

    public Integer getI_CENEIXH() {
        return I_CENEIXH;
    }

    public void setI_CENEIXH(Integer I_CENEIXH) {
        this.I_CENEIXH = I_CENEIXH;
    }

    public Integer getI_JIUBIAOCM() {
        return I_JIUBIAOCM;
    }

    public void setI_JIUBIAOCM(Integer I_JIUBIAOCM) {
        this.I_JIUBIAOCM = I_JIUBIAOCM;
    }

    public Integer getI_XINBIAODM() {
        return I_XINBIAODM;
    }

    public void setI_XINBIAODM(Integer I_XINBIAODM) {
        this.I_XINBIAODM = I_XINBIAODM;
    }

    public Integer getD_HUANBIAORQ() {
        return D_HUANBIAORQ;
    }

    public void setD_HUANBIAORQ(Integer D_HUANBIAORQ) {
        this.D_HUANBIAORQ = D_HUANBIAORQ;
    }

    public Integer getD_HUANBIAOHTSJ() {
        return D_HUANBIAOHTSJ;
    }

    public void setD_HUANBIAOHTSJ(Integer D_HUANBIAOHTSJ) {
        this.D_HUANBIAOHTSJ = D_HUANBIAOHTSJ;
    }

    public Integer getD_DENGJISJ() {
        return D_DENGJISJ;
    }

    public void setD_DENGJISJ(Integer D_DENGJISJ) {
        this.D_DENGJISJ = D_DENGJISJ;
    }

    public Integer getI_ZHUANGTAI() {
        return I_ZHUANGTAI;
    }

    public void setI_ZHUANGTAI(Integer I_ZHUANGTAI) {
        this.I_ZHUANGTAI = I_ZHUANGTAI;
    }

    public String getS_YANCHIYBH() {
        return S_YANCHIYBH;
    }

    public void setS_YANCHIYBH(String S_YANCHIYBH) {
        this.S_YANCHIYBH = S_YANCHIYBH;
    }

    public String getS_HUITIANYBH() {
        return S_HUITIANYBH;
    }

    public void setS_HUITIANYBH(String S_HUITIANYBH) {
        this.S_HUITIANYBH = S_HUITIANYBH;
    }

    public Integer getD_HUITIANSJ() {
        return D_HUITIANSJ;
    }

    public void setD_HUITIANSJ(Integer D_HUITIANSJ) {
        this.D_HUITIANSJ = D_HUITIANSJ;
    }

    public String getS_CHULIQK() {
        return S_CHULIQK;
    }

    public void setS_CHULIQK(String S_CHULIQK) {
        this.S_CHULIQK = S_CHULIQK;
    }

    public String getS_CAOZUOR() {
        return S_CAOZUOR;
    }

    public void setS_CAOZUOR(String S_CAOZUOR) {
        this.S_CAOZUOR = S_CAOZUOR;
    }

    public Integer getD_CAOZUOSJ() {
        return D_CAOZUOSJ;
    }

    public void setD_CAOZUOSJ(Integer D_CAOZUOSJ) {
        this.D_CAOZUOSJ = D_CAOZUOSJ;
    }

    public Integer getI_HUANBIAOFS() {
        return I_HUANBIAOFS;
    }

    public void setI_HUANBIAOFS(Integer I_HUANBIAOFS) {
        this.I_HUANBIAOFS = I_HUANBIAOFS;
    }

    public String getS_CHAOBIAOBZ() {
        return S_CHAOBIAOBZ;
    }

    public void setS_CHAOBIAOBZ(String S_CHAOBIAOBZ) {
        this.S_CHAOBIAOBZ = S_CHAOBIAOBZ;
    }

    public String getS_SHUIBIAOTXM() {
        return S_SHUIBIAOTXM;
    }

    public void setS_SHUIBIAOTXM(String S_SHUIBIAOTXM) {
        this.S_SHUIBIAOTXM = S_SHUIBIAOTXM;
    }

    public String getS_YANCHIYY() {
        return S_YANCHIYY;
    }

    public void setS_YANCHIYY(String S_YANCHIYY) {
        this.S_YANCHIYY = S_YANCHIYY;
    }

    public Integer getI_ZHENSHICM() {
        return I_ZHENSHICM;
    }

    public void setI_ZHENSHICM(Integer I_ZHENSHICM) {
        this.I_ZHENSHICM = I_ZHENSHICM;
    }

    public Integer getI_LINYONGSLSM() {
        return I_LINYONGSLSM;
    }

    public void setI_LINYONGSLSM(Integer I_LINYONGSLSM) {
        this.I_LINYONGSLSM = I_LINYONGSLSM;
    }

    public String getS_X() {
        return S_X;
    }

    public void setS_X(String S_X) {
        this.S_X = S_X;
    }

    public String getS_Y() {
        return S_Y;
    }

    public void setS_Y(String S_Y) {
        this.S_Y = S_Y;
    }

    public Integer getI_YANCHILX() {
        return I_YANCHILX;
    }

    public void setI_YANCHILX(Integer I_YANCHILX) {
        this.I_YANCHILX = I_YANCHILX;
    }

    public String getS_YANCHIBH() {
        return S_YANCHIBH;
    }

    public void setS_YANCHIBH(String S_YANCHIBH) {
        this.S_YANCHIBH = S_YANCHIBH;
    }

    public Integer getI_CHAOBIAOBZ() {
        return I_CHAOBIAOBZ;
    }

    public void setI_CHAOBIAOBZ(Integer I_CHAOBIAOBZ) {
        this.I_CHAOBIAOBZ = I_CHAOBIAOBZ;
    }

    public Integer getI_ShangChuanBZ() {
        return I_ShangChuanBZ;
    }

    public void setI_ShangChuanBZ(Integer I_ShangChuanBZ) {
        this.I_ShangChuanBZ = I_ShangChuanBZ;
    }

    public Integer getI_KaiZhangBZ() {
        return I_KaiZhangBZ;
    }

    public void setI_KaiZhangBZ(Integer I_KaiZhangBZ) {
        this.I_KaiZhangBZ = I_KaiZhangBZ;
    }

    public String getS_JH() {
        return S_JH;
    }

    public void setS_JH(String S_JH) {
        this.S_JH = S_JH;
    }

    public Integer getI_LIANGGAOSL() {
        return I_LIANGGAOSL;
    }

    public void setI_LIANGGAOSL(Integer I_LIANGGAOSL) {
        this.I_LIANGGAOSL = I_LIANGGAOSL;
    }

    public Integer getI_LIANGDISL() {
        return I_LIANGDISL;
    }

    public void setI_LIANGDISL(Integer I_LIANGDISL) {
        this.I_LIANGDISL = I_LIANGDISL;
    }

    public Integer getI_PINGJUNL1() {
        return I_PINGJUNL1;
    }

    public void setI_PINGJUNL1(Integer I_PINGJUNL1) {
        this.I_PINGJUNL1 = I_PINGJUNL1;
    }

    public Integer getI_SHANGCISL() {
        return I_SHANGCISL;
    }

    public void setI_SHANGCISL(Integer I_SHANGCISL) {
        this.I_SHANGCISL = I_SHANGCISL;
    }

    public Integer getN_JE() {
        return N_JE;
    }

    public void setN_JE(Integer N_JE) {
        this.N_JE = N_JE;
    }

    public String getS_JIETITS() {
        return S_JIETITS;
    }

    public void setS_JIETITS(String S_JIETITS) {
        this.S_JIETITS = S_JIETITS;
    }

    public String getS_ShangCiZTBM() {
        return S_ShangCiZTBM;
    }

    public void setS_ShangCiZTBM(String S_ShangCiZTBM) {
        this.S_ShangCiZTBM = S_ShangCiZTBM;
    }

}
